### ISSUE TITLE
Just a lot of things for improve

### ISSUE THREAD

**Issue by davidquintr** [MrSty/portfolio#1]
![image](https://github.com/MrSty/portfolio/assets/93105948/8284b9b5-b6d1-40dc-a0f9-ad8977bb1cbf)
This element needs to increase the line-height and letter-spacing.
![image](https://github.com/MrSty/portfolio/assets/93105948/ac2d3980-58bc-49f8-995c-16d94c9b3469)
This is with 1.2 of line-height
**Note:** In the breakpoint of mobile, loses their font-family.

### Only as a recomendation for the layout of certain elements, use the padding in the box that contains the paragraph and other things instead use the same property of padding for a lot of elements.
![image](https://github.com/MrSty/portfolio/assets/93105948/bd26d73c-9a67-4ff3-9781-a87d8644fd73)

This is better:
![image](https://github.com/MrSty/portfolio/assets/93105948/1a76c4c0-67f9-490d-ac9e-442c1f94675f)

### Center your social medias
![image](https://github.com/MrSty/portfolio/assets/93105948/f31403e9-f4b0-4562-a473-6db4760ea4f8)

Better:
![image](https://github.com/MrSty/portfolio/assets/93105948/381dd6c3-a902-4b44-a6b2-934bb9a4cb0f)

--- 
# Projects

![image](https://github.com/MrSty/portfolio/assets/93105948/da14b346-ee9a-46b5-bc68-7100e124c161)
- The technologies could be a square instead of rectangles and increase the size
- Avoid the use of box-shadow
- The bold text for the title currently looking bad.
- Align the margins of the text to the size of the projects:
![image](https://github.com/MrSty/portfolio/assets/93105948/928955c4-a370-498f-8a38-02d17d7400a6)

---
## General things

- I think that the margins (or width) of the viewport in mobile is not enough, change from 80% to 90% or 95%
- Attend Lighthouse warnings.

**Comment by MrSty** [comment]
Changes made, I made the adjustments you recommended, but I didn't understand the last part of the recommendations, I'm not sure what you were referring to.
